# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: #jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "Bhooraj"
description: "A blog about art and technology."
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: images/bhooraj-logo.png
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 100
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Montserrat"
    weights: "400,400i,700,700i"
  - name: "Vesper Libre"
    weights: "400,400i,700,700i"
google_analytics_four: UA-144707193-1 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: "bhoowrites" # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  works:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  # Recipe defaults
  - scope:
      path: "_works"
      type: works
    values:
      layout: post
      share: true
# Site Author
author:
  name: Bhooraj
  picture: /images/bhooraj.png
  email:
  twitter: "bhoowrites"
  links:
    - title: Twitter
      url: https://twitter.com/bhoowrites
      icon: fab fa-twitter-square
    - title: Facebook
      url: https://www.facebook.com/bhoowrites
      icon: fab fa-facebook-square      

# Footer Links
footer_links: false
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square

copyright: "© 2023 Bhooraj. The site uses a customised version of [So Simple](https://github.com/mmistakes/so-simple-theme) theme for Jekyll."
